---
title: "In-class Exercise 6"
author: "Yiwen Ding"
date: "Octorber 4, 2025"
date-modified: "last-modified"
execute: 
  eval: false
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(sf, terra, spatstat, knitr,
               tmap, rvest, tidyverse,
               plotly, sfdep)
```

### Importing Data

```{r}
mpsz <- read_rds("data/rds/mpsz_sf.rds")

BusStop = st_read(dsn = "data/geospatial/",
                  layer = "BusStop") %>%
  st_transform(crs = 3414)
  
odbus <- read_csv("data/aspatial/origin_destination_bus_202508.csv")
```

### Extracting Bus Stops within SG

```{r}
tm_shape(mpsz) +
  tm_polygons() + 

tm_shape(BusStop) +
  tm_dots() 
```

```{r}
st_crs(BusStop)
st_crs(mpsz)
```

```{r}
BusStop = st_read(dsn = "data/geospatial/",
                  layer = "BusStop") %>%
  st_transform(crs = 3414)

```

```{r}

BusStop <- st_transform(BusStop, st_crs(mpsz))

BusStop_in_SG <- st_join(
  BusStop, mpsz,
  join = st_within,
  left = FALSE
)
```

```{r}
tm_shape(mpsz) +
  tm_polygons() + 

tm_shape(BusStop_in_SG) +
  tm_dots()
```

### Deriving Analytical Hexagon

```{r}
hexagon <- st_make_grid(mpsz,
                        cellsize = 700,
                        what = "polygon",
                        square = FALSE) %>%
  st_sf()
```

### Filtering Hexagons with bus stops

```{r}
hexagon$n_collisions = 
  lengths(st_intersects(
    hexagon, BusStop_in_SG))

hexagon <- filter(hexagon, n_collisions > 0)
```

### Assigning ids to each hexagon

```{r}
hexagon <- hexagon %>%
  select( -n_collisions)

hexagon$HEX_ID <- sprintf(
  "H%04d", seq_len(nrow(hexagon))) %>%
  as.factor()

kable(head(hexagon))
```

## Preparing Trip Generation Data

### Cleaning data

```{r}
trips <- odbus %>%
  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%
  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%
  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%
  rename(TRPS = TOTAL_TRIPS) 
trips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)
kable(head(trips))
```

```{r}
bs_hex <- st_intersection(
  BusStop, hexagon) %>%
  st_drop_geometry() %>%
  select(c(BUS_STOP_N, HEX_ID))
kable(head(bs_hex))
```

```{r}
trips <- inner_join(trips, bs_hex)
kable(head(trips))
```
