---
title: "Hands-on Exercise 7"
author: "Yiwen Ding"

execute: 
  eval: false
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(olsrr, corrplot, ggpubr, 
               sf, sfdep, GWmodel, tmap, 
               tidyverse, gtsummary,
               performance, RColorBrewer)
```

### Geospatial Data Wrangling

```{r}
mpsz = st_read(dsn = "data/geospatial", 
               layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
mpsz_svy21 <- st_transform(mpsz, 3414)

st_crs(mpsz_svy21)

st_bbox(mpsz_svy21)
```

### Aspatial Data Wrangling

```{r}
condo_resale = read_csv(
  "data/aspatial/Condo_resale_2015.csv")
```

```{r}
glimpse(condo_resale)

head(condo_resale$LONGITUDE)
head(condo_resale$LATITUDE)
summary(condo_resale)
```

```{r}
condo_resale.sf <- st_as_sf(condo_resale,
                            coords = c("LONGITUDE", "LATITUDE"),
                            crs=4326) %>%
  st_transform(crs=3414)
```

```{r}
head(condo_resale.sf)
```

### Exploratory Data Analysis

```{r}
ggplot(data=condo_resale.sf, 
       aes(x=`SELLING_PRICE`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")
```

```{r}
AREA_SQM <- ggplot(data=condo_resale.sf, 
                   aes(x= `AREA_SQM`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

AGE <- ggplot(data=condo_resale.sf, 
              aes(x= `AGE`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_CBD <- ggplot(data=condo_resale.sf, 
                   aes(x= `PROX_CBD`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_CHILDCARE <- ggplot(data=condo_resale.sf, 
                         aes(x= `PROX_CHILDCARE`)) + 
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_ELDERLYCARE <- ggplot(data=condo_resale.sf, 
                           aes(x= `PROX_ELDERLYCARE`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_URA_GROWTH_AREA <- ggplot(data=condo_resale.sf, 
                               aes(x= `PROX_URA_GROWTH_AREA`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_HAWKER_MARKET <- ggplot(data=condo_resale.sf, 
                             aes(x= `PROX_HAWKER_MARKET`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_KINDERGARTEN <- ggplot(data=condo_resale.sf, 
                            aes(x= `PROX_KINDERGARTEN`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_MRT <- ggplot(data=condo_resale.sf, 
                   aes(x= `PROX_MRT`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_PARK <- ggplot(data=condo_resale.sf, 
                    aes(x= `PROX_PARK`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_PRIMARY_SCH <- ggplot(data=condo_resale.sf, 
                           aes(x= `PROX_PRIMARY_SCH`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

PROX_TOP_PRIMARY_SCH <- ggplot(data=condo_resale.sf, 
                               aes(x= `PROX_TOP_PRIMARY_SCH`)) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue")

ggarrange(AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, 
          PROX_ELDERLYCARE, PROX_URA_GROWTH_AREA,
          PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_MRT,
          PROX_PARK, PROX_PRIMARY_SCH, PROX_TOP_PRIMARY_SCH,  
          ncol = 3, nrow = 4)
```

```{r}
tmap_mode("view")

tm_shape(mpsz_svy21)+
  tm_polygons() +
tm_shape(condo_resale.sf) +  
  tm_dots(fill = "SELLING_PRICE",
          fill_alpha = 0.6,
          size = 0.5,
          fill.scale = tm_scale_intervals(
            style="quantile")) +
  tm_view(set_zoom_limits = c(11,14))

tmap_mode("plot")
```

### Hedonic Pricing Modelling in R

```{r}
condo.slr <- lm(formula=SELLING_PRICE ~ AREA_SQM, 
                data = condo_resale.sf)

summary(condo.slr)
```

```{r}
ggplot(data=condo_resale.sf,  
       aes(x=`AREA_SQM`, y=`SELLING_PRICE`)) +
  geom_point() +
  geom_smooth(method = lm)
```

```{r}
corrplot(cor(condo_resale[, 5:23]), 
         diag = FALSE, 
         order = "AOE",
         tl.pos = "td", 
         tl.cex = 0.5, 
         method = "number", 
         type = "upper")
```

```{r}
condo.mlr <- lm(
  formula = SELLING_PRICE ~ AREA_SQM + AGE  + 
    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +
    PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET   +
    PROX_KINDERGARTEN   + PROX_MRT  + PROX_PARK +
    PROX_PRIMARY_SCH + PROX_TOP_PRIMARY_SCH +
    PROX_SHOPPING_MALL  + PROX_SUPERMARKET + 
    PROX_BUS_STOP   + NO_Of_UNITS + 
    FAMILY_FRIENDLY + FREEHOLD, 
  data=condo_resale.sf)
summary(condo.mlr)
```

```{r}
condo.mlr1 <- lm(
  formula = SELLING_PRICE ~ AREA_SQM + AGE + 
    PROX_CBD + PROX_CHILDCARE + PROX_MRT +
    PROX_ELDERLYCARE    + PROX_URA_GROWTH_AREA +
    PROX_PARK   + PROX_PRIMARY_SCH + 
    PROX_SHOPPING_MALL  + PROX_BUS_STOP + 
    NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,
  data=condo_resale.sf)
summary(condo.mlr1)
```

```{r}
tbl_regression(condo.mlr1, intercept = TRUE)

tbl_regression(condo.mlr1, 
               intercept = TRUE) %>% 
  add_glance_source_note(
    label = list(sigma ~ "\U03C3"),
    include = c(r.squared, adj.r.squared, 
                AIC, statistic,
                p.value, sigma))
```

```{r}
check_collinearity(condo.mlr1)

mlr.vif <- check_collinearity(condo.mlr1)
plot(mlr.vif)
```

```{r}
check_model(condo.mlr1,
            check = "linearity")

check_normality(condo.mlr1)

plot(check_normality(condo.mlr1), 
     type = "qq")

check_model(condo.mlr1,
            check= "normality")
```

```{r}
mlr.output <- as.data.frame(condo.mlr1$residuals)

condo_resale.sf <- cbind(condo_resale.sf, 
                        condo.mlr1$residuals) %>%
rename(`MLR_RES` = `condo.mlr1.residuals`)

tmap_mode("view")

tm_shape(mpsz_svy21) +
  tm_polygons(fill_alpha = 0.4) +
tm_shape(condo_resale.sf) +  
  tm_dots(
    fill = "MLR_RES",
    size = 0.7,
    col = "black",
    fill.scale = tm_scale(
      n = 10,
      values = rev(
        brewer.pal(11, "RdBu")),
      style = "quantile",
      midpoint = NA),
    fill.legend = tm_legend(title = "Residuals")
  ) + 
  tm_title("LM Residuals (Quantile Classification)") +
  tm_layout(legend.outside = TRUE) +
  tm_view(set_zoom_limits = c(11,14))
```

```{r}
tmap_mode("plot")

condo_resale.sf <- condo_resale.sf %>% 
  mutate(
    nb = st_dist_band(
      st_geometry(geometry), 
                 upper = 1500),
    wt = st_weights(
      nb, style = "W"),
    .before = 1) 

set.seed(1234)
global_moran_perm(
  condo_resale.sf$MLR_RES, 
  nb = condo_resale.sf$nb, 
  wt = condo_resale.sf$wt,
  alternative = "two.sided", 
  nsim = 499)
```

### Building Hedonic Pricing Models using GWmodel

```{r}

```
