---
title: "Hands-on Exercise 9"
author: "Yiwen Ding"

execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tmap, SpatialAcc, sf, 
               ggstatsplot, reshape2,
               tidyverse)
```

### Preparing Data

```{r}
mpsz <- st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE_NO_SEA_PL")
```

```{r}
hexagons <- st_read(dsn = "data/geospatial", layer = "hexagons") 
```

```{r}
eldercare <- st_read(dsn = "data/geospatial", layer = "ELDERCARE") 
```

### Updating CRS Information

```{r}
mpsz <- st_transform(mpsz, 3414)
eldercare <- st_transform(eldercare, 3414)
hexagons <- st_transform(hexagons, 3414)
```

```{r}
st_crs(mpsz)
```

### Cleaning and updating attribute fields

```{r}
eldercare <- eldercare %>%
  select(fid, ADDRESSPOS) %>%
  mutate(capacity = 100)
```

```{r}
hexagons <- hexagons %>%
  select(fid) %>%
  mutate(demand = 100)
```

### Apsaital Data Handling and Wrangling

```{r}
ODMatrix <- read_csv("data/aspatial/OD_Matrix.csv", skip = 0)
```

```{r}
distmat <- ODMatrix %>%
  select(origin_id, destination_id, total_cost) %>%
  spread(destination_id, total_cost)%>%
  select(c(-c('origin_id')))

distmat_km <- as.matrix(distmat/1000)
```

### Modelling and Visualising Accessibility using Hansen

```{r}
acc_Hansen <- data.frame(ac(hexagons$demand,
                            eldercare$capacity,
                            distmat_km, 
                            #d0 = 50,
                            power = 2, 
                            family = "Hansen"))
```

```{r}
colnames(acc_Hansen) <- "accHansen"

acc_Hansen <- as_tibble(acc_Hansen)

hexagon_Hansen <- bind_cols(hexagons, acc_Hansen)
```

```{r}
acc_Hansen <- data.frame(ac(hexagons$demand,
                            eldercare$capacity,
                            distmat_km, 
                            #d0 = 50,
                            power = 0.5, 
                            family = "Hansen"))

colnames(acc_Hansen) <- "accHansen"
acc_Hansen <- as_tibble(acc_Hansen)
hexagon_Hansen <- bind_cols(hexagons, acc_Hansen)
```

```{r}
mapex <- st_bbox(hexagons)

tm_shape(hexagon_Hansen,
         bbox = mapex) + 
  tm_polygons(fill = "accHansen", 
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 10,
                values = "brewer.blues")) +
tm_shape(eldercare) +
  tm_dots(size = 0.3,
          fill = "red",
          col = "black") +
  tm_title("Accessibility to eldercare: Hansen method") +
  tm_layout(frame = TRUE) +
  tm_compass(type="8star", size = 2) +
  tm_scalebar() +
  tm_grid(alpha = 0.2)
```

```{r}
hexagon_Hansen <- st_join(hexagon_Hansen, mpsz, 
                          join = st_intersects)
```

```{r}
ggplot(data=hexagon_Hansen, 
       aes(y = log(accHansen), 
           x= REGION_N)) +
  geom_boxplot() +
  geom_point(stat="summary", 
             fun.y="mean", 
             colour ="red", 
             size=2)
```

### Modelling and Visualising Accessibility using KD2SFCA

```{r}
acc_KD2SFCA <- data.frame(ac(hexagons$demand,
                            eldercare$capacity,
                            distmat_km, 
                            d0 = 5,
                            power = 2, 
                            family = "KD2SFCA"))

colnames(acc_KD2SFCA) <- "accKD2SFCA"
acc_KD2SFCA <- as_tibble(acc_KD2SFCA)
hexagon_KD2SFCA <- bind_cols(hexagons, acc_KD2SFCA)
```

```{r}
tm_shape(hexagon_KD2SFCA,
         bbox = mapex) + 
  tm_polygons(fill = "accKD2SFCA", 
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 10,
                values = "brewer.blues")) +
tm_shape(eldercare) +
  tm_dots(size = 0.3,
          fill = "red",
          col = "black") +
  tm_title("Accessibility to eldercare: KD2SFCA method") +
  tm_layout(frame = TRUE) +
  tm_compass(type="8star", size = 2) +
  tm_scalebar() +
  tm_grid(alpha = 0.2)
```

```{r}
hexagon_KD2SFCA <- st_join(hexagon_KD2SFCA, mpsz, 
                          join = st_intersects)
```

```{r}
ggplot(data=hexagon_KD2SFCA, 
       aes(y = accKD2SFCA, 
           x= REGION_N)) +
  geom_boxplot() +
  geom_point(stat="summary", 
             fun.y="mean", 
             colour ="red", 
             size=2)
```

### Modelling and Visualising Accessibility using Spatial Accessibility Measure (SAM)

```{r}
acc_SAM <- data.frame(ac(hexagons$demand,
                         eldercare$capacity,
                         distmat_km, 
                         d0 = 5,
                         power = 2, 
                         family = "SAM"))

colnames(acc_SAM) <- "accSAM"
acc_SAM <- as_tibble(acc_SAM)
hexagon_SAM <- bind_cols(hexagons, acc_SAM)
```

```{r}
tm_shape(hexagon_SAM,
         bbox = mapex) + 
  tm_polygons(fill = "accSAM", 
              fill.scale = tm_scale_intervals(
                style = "quantile",
                n = 10,
                values = "brewer.blues")) +
tm_shape(eldercare) +
  tm_dots(size = 0.3,
          fill = "red",
          col = "black") +
  tm_title("Accessibility to eldercare: SAM method") +
  tm_layout(frame = TRUE) +
  tm_compass(type="8star", size = 2) +
  tm_scalebar() +
  tm_grid(alpha = 0.2)
```

```{r}
hexagon_SAM <- st_join(hexagon_SAM, mpsz, 
                       join = st_intersects)
```

```{r}
ggplot(data=hexagon_SAM, 
       aes(y = accSAM, 
           x= REGION_N)) +
  geom_boxplot() +
  geom_point(stat="summary", 
             fun.y="mean", 
             colour ="red", 
             size=2)
```
